### ISSUE TITLE
Running tests in the pipeline

### ISSUE THREAD

**Issue by bhamde** [actions-on-google/actions-on-google-testing-nodejs#22]
Hi,

We would like to run the tests we create in a pipeline (or anyone who pulls the code can just run them), but it says not to commit the test-credentials.json file, so what is the best way to go for that?

Thanks

**Comment by Fleker** [comment]
Unfortunately there's no good way, as this setup does require private credentials that would give one access to the Assistant as you.

If you are running this in a trusted environment, like within a group of folks in a company, you can use something like environment variables in a server that each person can access. For a more general project, you will probably have to ask them to generate these credentials and give them access to Cloud Project so that they can set it up in testing mode.
