### ISSUE TITLE
Library Alpha Discussion: Use promises or async/await?

### ISSUE THREAD

**Issue by Fleker** [actions-on-google/actions-on-google-testing-nodejs#7]
Hey AoG Devs!

Now that the alpha version of the testing library has been out for a few weeks, we'd like to get feedback on the behavior and API design of the library.

Right now the code is structured as a chain of Promises. This can make the code appear complex, especially as these test scripts do not need to be asynchronous.

Would it make sense to switch to await? This would mean that the developer needs Node 8 in their local environment. This would contrast with Firebase functions, which currently support Node 6. Samples in the AoG org have used features that were available in Node 6.

As these tests will most likely run locally, having sample code require Node 8 should not cause an issue.

### Using Node 6:
```javascript
return action.startConversation()
        .then(({ textToSpeech }) => {
            return action.send('cats');
        })
        .then(({ ssml }) => {
            expect(ssml[0]).to.have.string("Alright, here's a cat fact.")
            return action.endTest();
        })
```

### Using Node 8:
```javascript
const {textToSpeech} = await action.startConversation();
const {ssml} = await action.send(‘cats’);
expect(ssml[0]).to.have.string("Alright, here's a cat fact.")
action.endTest();
```

**Comment by AlexBravo** [comment]
Hi Nick,

Two things come to mind:
1. Are there plans to update AoG samples to Node sooner or later? If yes, using Node 8 in testing would be better.
2. If async not required, then sync is better as it's simpler to understand/debug

Overall, IMHO having fewer lines of code makes tests somewhat easier to maintain.

**Comment by yoichiro** [comment]
At least, I guess that currently most developers are still using node v6 to create actions for the Google Assistant, because most actions are deployed to the Could/Firebase functions. And, this library is for their actions. I think that we should not bring the cost to switch the node version between action codes and test codes. Thus, I think that it would be better to use node v6 until the node version of the cloud/firebase functions is updated to the node v8.
